# Generated by Django 3.2.5 on 2021-07-21 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuG_API', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='person',
            name='state',
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
