# Generated by Django 3.2.5 on 2021-07-21 17:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('TuG_API', '0002_auto_20210721_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='data_end',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 21, 17, 10, 33, 807603, tzinfo=utc), verbose_name='Fin de reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='data_start',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 21, 17, 10, 38, 216405, tzinfo=utc), verbose_name='Inicio de reserva'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='nit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='payment',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='person',
            name='payment_method',
            field=models.CharField(choices=[('Tarjeta', 'Tarjeta'), ('Transferencia', 'Transferencia'), ('Efectivo', 'Efectivo')], default='none', max_length=15),
        ),
        migrations.AddField(
            model_name='person',
            name='placement',
            field=models.CharField(choices=[('1A', 'Piso 1, cuarto A'), ('1B', 'Piso 1, cuarto B'), ('1C', 'Piso 1, cuarto C'), ('1D', 'Piso 1, cuarto D'), ('2A', 'Piso 2, cuarto A'), ('2B', 'Piso 2, cuarto B'), ('2C', 'Piso 2, cuarto C'), ('2D', 'Piso 2, cuarto D')], default='none', max_length=30),
        ),
        migrations.AddField(
            model_name='person',
            name='state_place',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Pagado', 'Pagado'), ('Eliminado', 'Eliminado')], default='none', max_length=10),
        ),
    ]
