# Generated by Django 3.2.5 on 2021-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuG_API', '0003_auto_20210721_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_end',
            field=models.DateTimeField(default='none', verbose_name='Fin de reserva'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_start',
            field=models.DateTimeField(default='none', verbose_name='Inicio de reserva'),
        ),
    ]
