# Generated by Django 3.2.5 on 2021-07-21 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TuG_API', '0004_auto_20210721_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='data_end',
            field=models.DateTimeField(verbose_name='Fin de reserva'),
        ),
        migrations.AlterField(
            model_name='person',
            name='data_start',
            field=models.DateTimeField(verbose_name='Inicio de reserva'),
        ),
    ]
